### PR TITLE
Added translation of Figma Text alignment to Tkinter 'anchor' property

### PR DESCRIPTION
**Pull request by neilbaldwin**
Figma uses LEFT, RIGHT, TOP, BOTTOM, CENTER for text alignment within a text frame whereas Tkinter uses N, S, E, W and CENTER.

This update adds some translation of the Figma 'textAlignHorizontal' and 'textAlignVertical' properites to Tkinter's 'anchor' property.

Note: this does not address the issue of the difference in parent 'object' that the alignment relates to. In Figma the alignment is relative to the Text Frame. Tkinter does not have a Text Frame widget and any Figma text is translated into a Text wdiget whoose aligment (the 'anchor' property) is relative to the Canvas itself.

As a consequence the only really reliable aligment settings in Figma is TOP and LEFT. This is default so should work most of the time but if the user has selected different alignment in Figma it will not translate correctly to Tkdesigner output.

This is an interim commit as coming up with a solution to this needs more thought and consideration than I have time for right now though I will come back to it in a couple of weeks.

### CODE REVIEW

**Comment by ParthJadhav** [comment]
That's great. I'll do more testing on it. 

> This is an interim commit as coming up with a solution to this needs more thought and consideration than I have time for right now though I will come back to it in a couple of weeks.

Let's discuss on this more :)

**Comment by neilbaldwin** [comment]
Hi,

I did some more investigating on this and I think I've exhausted every possible work-around to try to make the text alignment support work better. In short I just don't think it's possible. The ideal solution, as far as handling alignment that is...more aligned....with Figma would be to place the Text elements in their own Frame or Canvas inside the main window canvas but, frustratingly, Tkinter does not allow Frames or Canvas to have a transparent background colour. If this fix was made to Tkinter then this would be the best way to implement it.

Here's what I think is the best compromise while we're stuck with the limitations of Tkinter:

In the documentation/instructions: tell the user that in order to get consistent Text element results they must use LEFT and TOP alignment and also select the Automatic frame option (this snaps the Text Frame to the edges of the Text) and then manually position/align the Text element (i.e. not rely on RIGHT/CENTER/BOTTOM/JUSTIFIED alignment options.

What I can't decide is whether we should leave my FIgma-to-Tkinter alingment 'fix' (this PR) as is and let Tkdesigner generate out-of-alignment Text if the user doesn't specify the correct options in Figma. Or we could throw an error in Tkdesigner if a Text element is encountered that isn't set to LEFT-TOP-AUTO WIDTH? Or maybe a warning?

**Comment by ParthJadhav** [comment]
Hey @neilbaldwin , Thanks for the changes. 

> I did some more investigating on this and I think I've exhausted every possible work-around to try to make the text alignment support work better. In short I just don't think it's possible. The ideal solution, as far as handling alignment that is...more aligned....with Figma would be to place the Text elements in their own Frame or Canvas inside the main window canvas but, frustratingly, Tkinter does not allow Frames or Canvas to have a transparent background colour. If this fix was made to Tkinter then this would be the best way to implement it.

Even if we could do it, it wont be ideal. It would make the code more confusing and hard to debug.

> What I can't decide is whether we should leave my FIgma-to-Tkinter alingment 'fix' (this PR) as is and let Tkdesigner generate out-of-alignment Text if the user doesn't specify the correct options in Figma. Or we could throw an error in Tkdesigner if a Text element is encountered that isn't set to LEFT-TOP-AUTO WIDTH? Or maybe a warning?

Since the changes are not solving the problem then we don't need to merge it. And I like the idea of giving the users a short warning saying that the alignment is not LEFT-TOP. And also include a short paragraph on it in the instructions. 

What do you think ?

**Comment by neilbaldwin** [comment]
Yes, let's throw this PR in the bin then. I was hoping I'd be able to make the fix a bit more robust but it's clear it won't work 👍🏻

**Comment by ParthJadhav** [comment]
Yeah @neilbaldwin this could have been a great fix but Tkinter is very stubborn 😅

**Pull request closed without merging**
