### PR TITLE
Added Translations for Gujarati Language

### PR DESCRIPTION
**Pull request by Dev-Mehta**

### CODE REVIEW

**Comment by Dev-Mehta** [comment]
@ParthJadhav Yeah sure👍🏻

**Comment by piccoloser** [comment]
I'd also recommend renaming the files themselves to use `filename.gu.md` instead of underscores to fit the rest of the project.

**Comment by piccoloser** [comment]
Taking a closer look at `README_gu.md`, some of the HTML parameters were translated as well, breaking the file in those places. I'd recommend taking a little longer to correct those issues.

**Comment by Dev-Mehta** [comment]
@ParthJadhav @piccoloser I have added new commit and resolves those issues

**Comment by ParthJadhav** [comment]
Thanks @Dev-Mehta for the translation. I will merge it now!

**Pull request merged**
