### PR TITLE
Multithreading technology is added 增加了多线程技术

### PR DESCRIPTION
**Pull request by YouToco**
😊防止主程序在调用子函数(按下generate按钮)时卡顿

Prevent the main program from getting stuck when calling the sub function (press the ⌈generate⌋ button)

### CODE REVIEW

**Comment by YouToco** [comment]
If you have any questions, you can communicate with me

Or there's something wrong with my **code**

**Comment by ParthJadhav** [comment]
Hey Just tested the code. And it's great but the generate button is still clickable and functional  while the file is being generated. Can u add something which will show that the file is being generated ?

**Comment by YouToco** [comment]
Visualize the file creation progress by clicking on the Generate button. 
You can use the progress bar, 
which may include a method to calculate how many files need to be converted and how many files were converted, depending on how you converted from Figma files to Python files😃

**Comment by ParthJadhav** [comment]
I see, If we were to merge this change then we would also need to have some sort of indicator with it. Or else this might create confusion.

You can work on it if you want or let me know; I'll look into it.

**Review by ParthJadhav — COMMENTED** [review]
Hey @YouToco , can you modify this accordingly?

**Pull request closed without merging**
