### PR TITLE
Text width adjustment fix to stop unwanted wrapping. Maybe OS dependent (OSX)

### PR DESCRIPTION
**Pull request by neilbaldwin**
Because of the tiny size difference between the Figma font and the Tkinter font (could be OSX only, I can't test other platforms), sometime the text will wrap when you don't intend it to.

To test, this Figma file has two single-line text objects side-by-side. For me this renders incorrectly in Tkinter, wrapping the last word onto a second line.

https://www.figma.com/file/hNzdLAhQDcUSxMlq6JtZs3/Untitled?node-id=0%3A1

This fix adds a value to the Text element width equal to the font size which seems to be the best compromise.

### CODE REVIEW

**Review by SaptakBhoumik — DISMISSED** [review]

**Comment by ParthJadhav** [comment]
@SaptakBhoumik are you using windows ?

**Comment by SaptakBhoumik** [comment]
> @SaptakBhoumik are you using windows ?

No I am on Linux

**Comment by SaptakBhoumik** [comment]
>For me this renders incorrectly in Tkinter, wrapping the last word onto a second line.  

After the changes that @neilbaldwin made, I am not facing such issue but now the text is overlapping

**Comment by SaptakBhoumik** [comment]
Before 
image

After
Screenshot_3

@ParthJadhav 
I will try to fix it after you merge it

**Review by neilbaldwin — COMMENTED** [review]
I'd noticed that the image quality of small text on Buttons was quite poor. This PR addresses that by the following:

- requesting the Figma images at 2x the actual size
- changed the Button image loading code to use PIL and it's .resize method to scale the images by 50% and using the ANTIALIAS option
Before
After

**Comment by neilbaldwin** [comment]
@ParthJadhav don't merge yet, I've just noticed it breaks the regular Image element. Will test and fix.

**Comment by neilbaldwin** [comment]
OK this should be better for testing. I've done a few things:

- changed the loading code for regular Image elements to do the same X2 export -> 50% scale
- added some options in 'constants.py' to select between loading methods. You can choose None, 'PIL' or 'TK'
- added the various resampling methods as constants so you can choose between them

I only added the last two things so that we can do more testing. On OSX I found that 'PIL' using ANTIALIAS gives the best results on graphical elements such as button text. I've yet to do some comparissons on regular Image elements. Once we've decided which is the best method we can strip out these options (or leave them as options in the tool for a future feature?) and hard-code the chosen one.

**Comment by neilbaldwin** [comment]
Also, once we're happy with a merge for this feature I will refactor the code as it's a real mess with those IF...ELIF...ELSE sections now. 👍🏻

**Pull request closed without merging**
