### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/Tkinter-Designer/actions

### CODE REVIEW

**Comment by ParthJadhav** [comment]
May I know what it means ?

**Comment by cclauss** [comment]
bandit black codespell flake8 isort mypy pytest pyupgrade safety

These are a series of tools that test Python code in various ways.

**Comment by ParthJadhav** [comment]
Hey @cclauss, I don't know much about Github actions. So, Give me some time to learn about it and then I will merge the update if applicable. 

Thanks for the contribution.

**Comment by ParthJadhav** [comment]
Hey @cclauss, Can we only use Black and iSort as I think other uses are not needed. Also make them automatic, as in they should format the code automatically. 

Also can we make an workflow which would test tkinter_designer.py on Windows, MacOS and Linux. It should run it and check if any errors are found. This will save our time in testing the code on different platforms and wait for the results.

**Pull request closed without merging**
