### PR TITLE
Change Button to Label

### PR DESCRIPTION
**Pull request by omar2205**

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Hey @omar2205  Thanks for the PR. I'll be reviewing the changes soon and will get back to you. Sorry for the delay.

**Comment by ParthJadhav** [comment]
Hey @omar2205 , I tested this and didn't find satisfying results :- 

image

**Comment by ParthJadhav** [comment]
Here's the test file.

https://www.figma.com/file/WVLnulVsI177tvnxSdqOUZ/Example-File?node-id=913%3A2

**Comment by omar2205** [comment]
Try this one. I must have forgotten to push this.

Check this repo: https://github.com/omar2205/imgs-lottie

**Comment by ParthJadhav** [comment]
I'll test this commit. Thanks !

**Comment by ParthJadhav** [comment]
```
  File "C:\Users\Admin\development\Tkinter-Designer\build\gui.py", line 130, in <module>
    button_1 = Label(
NameError: name 'Label' is not defined
```

I also realized that even if it improved the result. That's not the right thing to do. because most of the users would want it to be Button and not a label. It would create confusion.

**Comment by ParthJadhav** [comment]
Unfortunately, I won't be able to merge this PR. Thanks for taking the efforts @omar2205 .

**Comment by omar2205** [comment]
My point was, buttons have active state that is hard to get rid off. And they look ugly. In Figma you would call it a button but under the hood it will be a label.

Anyways, do what you want. When I use this to generate GUIs, I will change every Button to a Label.

**Pull request closed without merging**
