### PR TITLE
Fix translation links in README and instructions

### PR DESCRIPTION
**Pull request by piccoloser**
Some links were broken when `README.md` was capitalized, and some links were inconsistent/missing.

### CODE REVIEW

**Comment by piccoloser** [comment]
I think that, for simplicity's sake, as more translations are added, it would be beneficial to require the contributor to update the links in all README files. I don't think it'd be a bad thing if one "Translations" section were simply copy/pasted across all the files, even if it would lead to each file linking to itself once.

Also, I wanted to note the order in which the languages are listed. I've simply listed them in alphabetical order according to the romanization of each language (**C**hinese, **E**nglish, **F**rench, **G**ujarati).

# Example

```
## Translations
- [简体中文](docs/README.zh-CN.md)
- [English](/README.md)
- [Français](docs/README.fr-FR.md)
- [ગુજરાતી](docs/README.gu-GU.md)
```

**Comment by ParthJadhav** [comment]
Yes, I agree with that @piccoloser . I'll be merging this change.
Thanks !

**Comment by ParthJadhav** [comment]
Hey @piccoloser , The changes in the PR have broken links due to uppercase "Readme" in the links.

**Comment by piccoloser** [comment]
Oof, that's ironic. Let me take a look and I'll fix it!

**Comment by piccoloser** [comment]
@ParthJadhav I figured out what the issue was. I renamed all the README files with full capitalization, but for some reason that wasn't included in my commits. The issue would be fixed by just capitalizing the files.

Not sure why that wasn't included in the commits, I'll have to check on my environment.

**Comment by piccoloser** [comment]
@ParthJadhav Sorry for the double-tag. Should be fixed now.

**Comment by ParthJadhav** [comment]
Awesome @piccoloser . But there are still some broken links. 
Chinese Readme -> Gujrati Readme (You missed a forward slash)
French Readme -> All other Readme
Gujarati Readme -> All other Readme

**Review by ParthJadhav — CHANGES_REQUESTED** [review]

**Review by ParthJadhav — APPROVED** [review]

**Comment by piccoloser** [comment]
Okay, I'll take another look.

**Comment by piccoloser** [comment]
Okay, I think that fixes it.

**Comment by ParthJadhav** [comment]
Yes ! Thanks for it. I can merge it now.

**Pull request merged**
