### PR TITLE
Linux Fix (Iconbitmap)

### PR DESCRIPTION
**Pull request by Shaco74**
Added images/iconbitmap.gif (converted images/iconbitmap.ico)

tkinter_designer.py now uses the new iconbitmap.gif when the os is Linux. 

I could only test so far that the script isnt crashing or anything. BUT I am using GNOME which doesnt have any window icons. I am very confident that it will work on KDE for example but i cannot confirm. 
Still this fix will mostly (if not fully) allow Linux support for now hopefully.

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Thanks for making the improvements, I will test it and merge it.

**Comment by ParthJadhav** [comment]
Hey @Shaco74, Can you test the code by only using GIF's ? 
Means try changing app_icon.ico to GIF and then using it for all the platforms. If Gif's work for all then why use .ico. We could get rid of that if else block.

**Comment by Shaco74** [comment]
@ParthJadhav  
Hey. Just woke up. 
I will test it on windows and on a Linux distro which uses window icons. 
Give me 1-2 hours 👍

**Comment by ParthJadhav** [comment]
No, I think you got it wrong. What I am telling is that try the Icon which you used for linux for windows. Means use GIF for windows too.

**Comment by ParthJadhav** [comment]
Cool, Since it's working on windows too. I can merge it.

Great work, Thanks!

**Comment by Shaco74** [comment]
Yeah it works on windows. I am currently setting up KDE on my Ubuntu machine to test if the icon will get displayed correctly. 
If it works I just have to clean up the code afterwards. 

In addition I found out that the os().uname() method wasn't supported anyways in windows.

**Comment by ParthJadhav** [comment]
Oh, Cool. After you've done checking and cleaning we can merge it. It was better we tested it or else os.uname would have caused crashes.

**Comment by ParthJadhav** [comment]
Great ! Merging it.

**Comment by Shaco74** [comment]
Screenshot_20210608_125124
Icon is displaying! 
You should be able to merge it without further concerns.

But i found another file in the *images* folder. **app_icon.ico** could give us trouble in the future

**Comment by ParthJadhav** [comment]
That file is for Icon of the executables, and Pyinstaller supports ico files

**Pull request merged**
